import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Sidebar from "@/app/components/Sidebar";

const inter = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex bg-gray-100 min-h-screen justify-end">
          <Sidebar />
          <main className="w-[calc(100%-240px)] min-h-screen p-6 bg-gray-100">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
